# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---
include:
  - board: corne_choc_pro_left
    shield: nice_view
  - board: corne_choc_pro_right
    shield: nice_view

  - board: corne_choc_pro_left
    shield: settings_reset
  - board: corne_choc_pro_right
    shield: settings_reset

  - board: crosses_v2_left
    artifact-name: crosses_v2_36_left
  - board: crosses_v2_right
    artifact-name: crosses_v2_36_right
 
  - board: crosses_v2_right
    artifact-name: crosses_v2_settings_reset
    shield: settings_reset
